from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


SUPPORTED_STAGE1_BUILTIN_FAMILIES = frozenset(
    {
        "repetition_code:memory",
        "rotated_surface_code",
        "unrotated_surface_code",
        # "toric_code" is in the Stage 1 catalog but not natively generated by stim.Circuit.generated;
        # it will be added via a manual generator in a future increment.
    }
)


@dataclass(frozen=True, slots=True)
class CodeSpec:
    family: str
    distance: int
    rounds: int
    logical_basis: str = "Z"
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.family not in SUPPORTED_STAGE1_BUILTIN_FAMILIES:
            raise ValueError(f"Unsupported Stage 1 built-in family: {self.family!r}")
